# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38238f0a1fec86664e8109efa1324e0b752a86d598ec595f6ecea7f80049a8b3f9cd7f2ee63cfddc0462d223b8779c45b6d4860ec3e73692d79ba71fffeea92d

test:
  secret_key_base: 1b489392db87742b139d8a72d332fd54f254e2e4cc52faf0c218ad17be11bf2fef0b06d2898678aaae0f71e5ddbcf83186d615813a74e1458ea2de428ffc9bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
